# Generated by Django 4.2.7 on 2025-08-29 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('lat', models.DecimalField(decimal_places=6, help_text='Current latitude', max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, help_text='Current longitude', max_digits=9)),
                ('accuracy', models.DecimalField(decimal_places=2, help_text='GPS accuracy in meters', max_digits=5)),
                ('geofence_verified', models.BooleanField(default=False, help_text='Whether geofence check passed')),
                ('face_verified', models.BooleanField(default=False, help_text='Whether face verification passed')),
                ('status', models.CharField(choices=[('present', 'Present'), ('fail_geo', 'Geofence Failed'), ('fail_face', 'Face Verification Failed'), ('fail_both', 'Both Failed')], default='fail_both', max_length=20)),
                ('device_info', models.TextField(blank=True, help_text='Device information')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
                'db_table': 'attendance_logs',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text="Admin's response")),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeofenceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(help_text='Company/Organization name', max_length=100, unique=True)),
                ('radius', models.DecimalField(decimal_places=2, default=30.0, help_text='Geofence radius in meters', max_digits=6)),
                ('accuracy_threshold', models.DecimalField(decimal_places=2, default=25.0, help_text='GPS accuracy threshold in meters', max_digits=5)),
                ('center_lat', models.DecimalField(decimal_places=6, help_text='Center latitude of geofence', max_digits=9)),
                ('center_lon', models.DecimalField(decimal_places=6, help_text='Center longitude of geofence', max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Geofence Setting',
                'verbose_name_plural': 'Geofence Settings',
                'db_table': 'geofence_settings',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Setting key', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Setting value')),
                ('description', models.TextField(blank=True, help_text='Setting description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
