# Generated by Django 4.2.7 on 2025-09-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_company_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='lat',
            field=models.DecimalField(decimal_places=6, help_text='Center latitude of company', max_digits=9),
        ),
        migrations.AlterField(
            model_name='company',
            name='lon',
            field=models.DecimalField(decimal_places=6, help_text='Center longitude of company', max_digits=9),
        ),
        migrations.AlterField(
            model_name='company',
            name='radius',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Default geofence radius in meters', max_digits=6),
        ),
    ]
