# Generated by Django 4.2.7 on 2025-10-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_company_lat_alter_company_lon_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='attendance_type',
            field=models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out')], default='check_in', max_length=10),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='check_in_time',
            field=models.TimeField(blank=True, help_text='Check-in time', null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='check_out_time',
            field=models.TimeField(blank=True, help_text='Check-out time', null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='total_time_minutes',
            field=models.IntegerField(blank=True, help_text='Total time spent in minutes', null=True),
        ),
    ]
