# Generated by Django 4.2.7 on 2025-10-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancelog_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='radius',
            field=models.DecimalField(decimal_places=2, default=150.0, help_text='Default geofence radius in meters', max_digits=6),
        ),
    ]
