# Generated by Django 4.2.7 on 2025-10-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_update_company_radius_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, help_text='GPS accuracy in meters', max_digits=9),
        ),
    ]
